### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by eschaefer** [securitywithoutborders/website#28]
- Add notes to README about how to add a blog post
- Mention the review process
- Find a place to link from the home page (see @Tethik 's draft)

**Comment by Tethik** [comment]
Link to draft: https://github.com/Tethik/securitywithoutborders.github.io/tree/new_design

**Comment by hacker-hacker** [comment]
Some wishes from @botherder:

* wider
* a more visible menu
* slightly bigger default font
* some better solution with the placement of the logo perhaps

**Comment by Tethik** [comment]
Done!
