### ISSUE TITLE
Give me the ability for anyone to make wiki pages?

### ISSUE THREAD

**Issue by elimisteve** [securitywithoutborders/website#4]
Either here or in a new repo? Thanks!

**Comment by elimisteve** [comment]
Seems useful (as per some people's comments), though if you want to stick with etherpad that's fine with me

**Comment by Tethik** [comment]
What do you want to write there? This repo is afaik only for the website, not the org itself.

**Comment by Tethik** [comment]
This repo should be more suited: https://github.com/securitywithoutborders/organization
Closing.

**Comment by elimisteve** [comment]
Thanks @Tethik that repo sounds great :-).
