### ISSUE TITLE
Small suggestion - French translation

### ISSUE THREAD

**Issue by Ayms** [securitywithoutborders/website#45]
Small detail but "face increasing threats and persecution online" is translated by "sont plus que jamais menacés``..``", I would add "sont plus que jamais menacés et la cible de représailles.", at the same time you can remove the double dot highlighted above, litterally this should give something like "de représailles en ligne" or "de représailles sur internet" but not sure what's the added value of "online" in the original english text and if it applies to both "threats" and "persecution", or maybe the closest could be "sont de plus en plus menacés sur internet et la cible de représailles"

**Comment by Tethik** [comment]
We've recently moved our translations to Transifex. If you could kindly add this as a suggestion there instead we would appreciate it. This link should take you to the right place:
https://www.transifex.com/security-without-borders/security-without-borders-website/translate/#fr/enyml/107245913

Thanks!

**Comment by Ayms** [comment]
Yes I know, but I am a bit reluctant to open a Transifex account, in addition for so small changes  (Veronica in fact told me to go here instead)

**Comment by Tethik** [comment]
Oh alright, I wasnt aware. Disregard what I said then and lets carry on the conversation here.

I'd still appreciate if eventual changes end up on transifex though, would save me some trouble :)

**Comment by Ayms** [comment]
Maybe we could discuss/(agree on) this small matter here and then someone put the final text on Transifex, no?

I think the best translation is "sont de plus en plus menacés sur internet et la cible de représailles"

**Comment by Tethik** [comment]
Sorry for not replying earlier, not a french speaker so I unfortunately can't really say much on this. I copied your suggestions to Transifex though.

**Comment by Tethik** [comment]
Closing this for now. Feel free to reopen or make the changes on transifex.
