### ISSUE TITLE
Translate to more languages

### ISSUE THREAD

**Issue by deralexxx** [securitywithoutborders/website#7]
Given the target audience it would be handy to have translations in more then the current two languages, maybe someone can pick up french, spanish etc?
@Rafiot maybe?

**Comment by nashe** [comment]
I'm picking french. We are already 5 native speakers on Mattermost, we should be able to make something correct :-)

**Comment by JusticeRage** [comment]
I'll be helping with the French translation as well!

**Comment by eschaefer** [comment]
@nashe @JusticeRage Thanks! Just open a pull request with your version when you can, and we'll get it merged. Just add the new `fr.yml` file in `/locales/`.

**Comment by Tethik** [comment]
We now have a Transifex project where we will handle the translations.

https://www.transifex.com/security-without-borders/security-without-borders-website/
